version: 2

jobs:
  prepare:
    docker:
      - image: circleci/node:10.8.0-stretch-browsers

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make init
      - persist_to_workspace:
          root: .
          paths:
            - "./*"

  test:
    docker:
      - image: circleci/node:10.8.0-stretch-browsers

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint scripts and stylesheets
          command: make lint -j
      - run:
          name: Check formatted sources
          command: make check_format -j

workflows:
  version: 2
  test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
